### ISSUE TITLE
[Bug] WDA无法在XCode15，iOS17上跑起来，通过hook方法能跑起来之后，但是Sib调用会失败

### ISSUE THREAD

**Issue by guoxiangyang163** [SonicCloudOrg/sonic-ios-wda#50]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sib: version: 1.3.13
sgm: version: 1.3.4

### Deploy platform

Agent 部署在MAC OS上

### Minimal reproduce step

一开始，我用WDA在XCode15，iOS17上跑不起来，run test之后，点击真机上WDA图标会闪退，我在github上找到了类似问题，
按照https://github.com/appium/WebDriverAgent/pull/800这上面的方法做了之后，WDA能跑起来了，但是用sonic Agent里的Sib调用还是不行，log报错为WebDriverAgent server start failed: receive packet: InvalidService，请问应该怎么办

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by guoxiangyang163** [comment]
https://github.com/appium/WebDriverAgent/pull/800
上述链接是这个

**Comment by ZhouYixun** [comment]
所以这不是wda的问题，非常感谢
