### ISSUE TITLE
[Bug] 直接Xcode在真机上跑正常，打成IPA包之后调起会闪退

### ISSUE THREAD

**Issue by guoxiangyang163** [SonicCloudOrg/sonic-ios-wda#51]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sib: version: 1.3.13
sgm: version: 1.3.4

### Deploy platform

iPhone XR
iOS 15,4

### Minimal reproduce step

我在使用WDA的时候，直接通过XCode在真机上跑是没问题的，通过点击或Sib启动都正常，但把WDA打成IPA包之后，通过Sib进行安装后再启动WDA就会闪退，不是必现但出现概率很大。crash日志是如下
[crash.txt](https://github.com/SonicCloudOrg/sonic-ios-wda/files/13726790/crash.txt)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
不清楚，一般不建议打成ipa
