### ISSUE TITLE
[Bug] iOS版本17.5.1，崩溃

### ISSUE THREAD

**Issue by JJXYZ** [SonicCloudOrg/sonic-ios-wda#62]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

main分支，直接下载的

### Deploy platform

macos Sonoma 14.6

### Minimal reproduce step

xcode直连手机，iOS版本17，Xcode版本Version 15.4 ，macos Sonoma 14.6，选择 Product -> Test，运行到手机上正常打开，断开电脑，点击手机上生成的WebDriver App，崩溃

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你可以更多去了解wda怎么运行的，wda并不是点击app运行的，更何况离开了电脑
