### ISSUE TITLE
[Bug] 用之前的wda没问题 更新后报错了

### ISSUE THREAD

**Issue by Pycoder0901** [SonicCloudOrg/sonic-ios-wda#63]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

最新

### Deploy platform

macOS

### Minimal reproduce step

异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Unhandled endpoint: /session/879C4356-3A64-4A7D-9B44-65AFEB4ED93D/wda/touch/multi/perform -- http://127.0.0.1:62257/ with parameters {
    wildcards =     (
        "session/879C4356-3A64-4A7D-9B44-65AFEB4ED93D/wda/touch/multi/perform"
    );
}

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
> ### Search before asking
> * [x]  I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。
> 
> ### Sonic version
> 最新
> 
> ### Deploy platform
> macOS
> 
> ### Minimal reproduce step
> 异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Unhandled endpoint: /session/879C4356-3A64-4A7D-9B44-65AFEB4ED93D/wda/touch/multi/perform -- http://127.0.0.1:62257/ with parameters { wildcards = ( "session/879C4356-3A64-4A7D-9B44-65AFEB4ED93D/wda/touch/multi/perform" ); }
> 
> ### Are you willing to submit a PR?
> * [x]  I'm willing to submit a PR! | 我将发起PR！

需要更新到最新sonic版本，因为wda新版本有废弃了部分接口哦。如果你是单独用sonic-server-core的用户，也是用最新maven包就可以了
